name: discovered-weekly

# on:
#     workflow_dispatch:
#     schedule:
#         # Run every Tuesday at 0 UTC
#         - cron: "0 0 * * 2"
on:
  pull_request:
jobs:
  run-tests:

# jobs:
    # build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run main
              env:
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                  USERNAME: ${{ secrets.USERNAME }}
                  DISCOVER_WEEKLY_PLAYLIST_ID: ${{ secrets.DISCOVER_WEEKLY_PLAYLIST_ID }}
                  ALL_DISCOVERED_PLAYLIST_ID: ${{ secrets.ALL_DISCOVERED_PLAYLIST_ID }}
              run: python main.py
            - name: 'Install Snowmate Runner'
              run: pip install -i "https://${{ secrets.SNOWMATE_CLIENT_ID_L }}:${{ secrets.SNOWMATE_SECRET_KEY_L }}@pypi.snowmate.io/simple" -U snowmate_runner
            - name: 'Run Snowmate Tests'
              uses: snowmate/snowmate-runner-action@latest
              with:
                project-path: .  # If this repo is not a monorepo, insert "." (dot without the apostrophes).
                project-id: 650c6fe0a66c94ade6d4718d  # Insert your project ID
                client-id: ${{ secrets.SNOWMATE_CLIENT_ID_L }}
                secret-key: ${{ secrets.SNOWMATE_SECRET_KEY_L }}
                github-token: ${{ secrets.GITHUB_TOKEN }}  # Provided by default by GitHub.

          
          
